- id: phpmd
  name: PHP Mess Detector
  description: Run phpmd to detect code smells and possible errors
  language: script
  files: \.php$
  entry: scripts/phpmd.sh
  args: ["ansi", "cleancode,codesize,controversial,design,naming,unusedcode"]
