- id: phpmd
  name: PHP mess detector
  description: Run phpmd to detect code smells and possible errors
  language: script
  files: \.php$
  entry: phpmd
  args: ["ansi", "cleancode,codesize,controversial,design,naming,unusedcode"]

- id: docker-phpmd
  name: PHP mess detector
  description: Run phpmd to detect code smells and possible errors in Docker container
  language: docker_image
  files: \.php$
  entry: daverona/pre-commit-php phpmd
  args: ["ansi", "cleancode,codesize,controversial,design,naming,unusedcode"]
