- id: phpmd
  name: PHP Mess Detector
  description: Run `phpmd` to find possible bugs, suboptimal code, overcomplicated expressions, and so on
  language: script
  files: \.php$
  entry: pre-commit-hooks/phpmd.sh
  args: ["ansi", "cleancode,codesize,controversial,design,naming,unusedcode"]

- id: docker-phpmd
  name: PHP Mess Detector
  description: Run `phpmd` to find possible bugs, suboptimal code, overcomplicated expressions, and so on
  language: docker_image
  files: \.php$
  entry: daverona/pre-commit-php phpmd.sh
  args: ["ansi", "cleancode,codesize,controversial,design,naming,unusedcode"]
